eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8971/eureka/,http://server2:8972/eureka/
server:
  port: 8993
spring:
  application:
    name: user
  zipkin: 
    base-url: http://localhost:8995
feign:
  hystrix:
    enabled: true
