eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8971/eureka/,http://server2:8972/eureka/
server:
  port: 8994
spring:
  application:
    name: zuul
zuul:
  routes:
    api-u:
      path: /api-u/**
      serviceId: user
    api-p:
      path: /api-p/**
      serviceId: parking
    api-c:
      path: /api-c/**
      serviceId: common