eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8971/eureka/,http://server2:8972/eureka/
server:
  port: 8991
spring:
  application:
    name: common
  zipkin: 
    base-url: http://localhost:8995
